name: cloudged
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  mime: ^0.9.6+3
  file_picker: ^1.9.0+1
  simple_animations: ^2.2.0
  flutter_material_color_picker: ^1.0.5
  intl: ^0.16.1
  #intl_translation: ^0.17.10
  flutter_localizations:
    sdk: flutter
  url_launcher: ^5.4.5
  email_validator: ^1.0.4
  image_picker: ^0.6.6+1
  location_permissions: ^2.0.5
  brasil_fields: ^0.0.9
  uuid: ^2.0.4
  cloud_firestore: ^0.13.5
  firebase_storage: ^3.1.5
  firebase_database: ^3.1.5
  firebase_auth: ^0.16.0
  firebase_analytics: ^5.0.11
  firebase_core: ^0.4.4+3
  font_awesome_flutter: ^8.8.1
  flutter_svg: ^0.17.4
  dio: ^3.0.9
  flutter_mobx: ^1.1.0
  mobx: ^1.1.1
  flutter_modular: ^1.1.2
  google_sign_in: ^4.4.4
  flutter_icons: ^1.1.0

  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  mockito: ^4.1.1
  mobx_codegen: ^1.0.3
  build_runner: ^1.9.0
  flutter_test:
    sdk: flutter
  effective_dart: ^1.2.0


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/svgs/
   - assets/images/

   
fonts:
    - family: Google
      fonts:
        - asset: assets/fonts/ProductSans-Regular.ttf
        - asset: assets/fonts/ProductSans-Bold.ttf
          weight: 700 
scripts:
  mobx: flutter pub get & flutter pub run build_runner watch --delete-conflicting-outputs
